import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ipronto/header";
import FooterComponent from "@/components/ipronto/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
